### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by yoDon** [Intuitive-Systems/react-agent-ts#10]
I saw that you added a license, and wanted to make sure you were aware the Creative Commons organization itself explicitly recommends not using their licenses for software (https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). 

The Yohei's Baby Agi project that you mention in some of your PRs is MIT licensed. Using the same license as that project will increase the ease with which features can be ported between the projects, increasing the speed of adoption of your project. It's also one of the most popular open source licenses which means basically all organizations have policies in place for using MIT licensed code.

 It's certainly 100% your choice what license to choose, including having the freedom to choose a non-standard license (like Creative Commons) or a more restrictive license like one of the GPL variants, but you should be aware that doing so will greatly reduce adoption of the project because of the number of organizations that have restrictions prohibiting their engineers from using code licensed other than with MIT, BSD-2, or Apache. My view is the project you've launched here is extremely important and should be licensed with MIT, like Yohei's Baby Agi, because that's by far the most common license choice for projects in the NodeJS/TypeScript ecosystems, guaranteeing that it's a license all developers and all organizations involved in the project will be comfortable using.

License choice mattera and Is hard to change once a project has a lot of contributors. The NodeJS/TypeScript ecosystem is almost entirely an MIT-licensed ecosystem. This project is new but it's too important to leave hampered with a non-standard license.

**Comment by yourbuddyconner** [comment]
Appreciate your thoughts @yoDon -- went ahead and refactored some things and applied an Apache 2.0 license to the base code. 

I feel Apache 2.0 is the most compatible with my personal views on software licensing. Free (as in _free!_) Software FTW!
