### ISSUE TITLE
Where do I get retrieval plugin api key?

### ISSUE THREAD

**Issue by gorilla-san** [Intuitive-Systems/react-agent-ts#2]
1. Where do I get retrieval api key
2. What serp? Any serp? 

Am I just a noob.

**Comment by yourbuddyconner** [comment]
1. Retrieval API Key is the bearer token that the local retrieval api uses, you will have to read through the repo unfortunately to get more info on how you need to use it
2. Serp Google Search API: https://serpapi.com/
